spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:H:/test/img

server:
  port: 8084

logging:
  file: H:\test\log\project1.log
  level:
    com:
      cskaoyan:
        mapper: debug


